import { Inter } from "next/font/google";
import "./globals.css";
import { StickyNavbar } from "@/Components/NavBar";
import { Providers } from "./GlobalRedux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <StickyNavbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
